SELECT 
    {{ generate_surrogate_key(["\"Id\""]) }} AS person_id,
    0 AS gender_concept_id,
    DATE_PART('year', "BIRTHDATE") AS year_of_birth,
    DATE_PART('month', "BIRTHDATE") AS month_of_birth,
    DATE_PART('day', "BIRTHDATE") AS day_of_birth,
    NULL AS birth_datetime,
    0 AS race_concept_id,
    0 AS ethnicity_concept_id,
    NULL AS location_id,
    NULL AS provider_id,
    NULL AS care_site_id,
    "Id" AS person_source_value,
    NULL AS gender_source_value,
    0 AS gender_source_concept_id,
    NULL AS race_source_value,
    0 AS race_source_concept_id,
    NULL AS ethnicity_source_value,
    0 AS ethnicity_source_concept_id
FROM {{ ref('patients') }} 
