name: "synthea_omop_etl"
version: "0.1.0"
config-version: 2

profile: "synthea_omop_etl"

asset-paths: ["assets"]
docs-paths: ["docs"]
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"

vars:
  seed_source: true

models:
  synthea_omop_etl:
    intermediate:
      +materialized: table
      +docs:
        node_color: '#FBC511'
    omop:
      +materialized: table
      +docs:
        node_color: '#EB6622'
    staging:
      synthea:
        +materialized: view
        +docs:
          node_color: '#336B91'
      vocabulary:
        +materialized: view
        +docs:
          node_color: '#336B91'
      map:
        +materialized: view
        +docs:
          node_color: '#336B91'

seeds:
  +quote_columns: true
  synthea_omop_etl:
    map:
      +enabled: true
      +schema: map_seeds
      +docs:
        node_color: '#69AED5'
    vocabulary:
      +enabled: true
      +schema: vocab_seeds
      +docs:
        node_color: '#69AED5'
    synthea:
      +enabled: true
      +schema: synthea_seeds    
      +docs:
        node_color: '#69AED5'
