name: Test dbt duckdb

on:
  push:
    branches:
      - '**'
    paths:
      - macros/**
      - models/**
      - scripts/**
      - seeds/**
      - snapshots/**
      - tests/**
      - dbt_project.yml
      - .github/workflows/**
  workflow_dispatch:

jobs:
  test-dbt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies with uv
        run: uv sync --group duckdb

      - name: Setup DBT profile
        run: |
          mkdir -p ~/.dbt
          cat << EOF > ~/.dbt/profiles.yml
          synthea_omop_etl:
            outputs:
              dev:
                type: duckdb
                path: synthea_omop_etl.duckdb
                schema: dbt_synthea_dev
            target: dev
          EOF
          
      - run: uv run dbt deps
      - run: uv run dbt seed
      - run: uv run dbt run
      - run: uv run dbt test

      - name: Generate DBT Docs
        run: uv run dbt docs generate
